services:
  postgres:
    image: postgres:16-alpine
    container_name: task_manager_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager_db

    ports:
      - "51213:5432"

    volumes:
      - taskmanager_pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: task_manager_backend
    restart: unless-stopped

    env_file:
      - ./backend/.env

    ports:
      - "8080:8080"

    volumes:
      - ./backend:/app
      - /app/node_modules

    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: task_manager_frontend
    restart: unless-stopped

    env_file:
      - ./frontend/.env

    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

    depends_on:
      - backend

volumes:
  taskmanager_pg_data: